### ISSUE TITLE
[W4 - geospatial-data-project] Sonia Garcia Fominaya

### ISSUE THREAD

**Issue by Fominayasg** [Ironhack-Data-Madrid-Enero-2021/W4-geospatial-data-project#1]
https://github.com/Fominayasg/geospatial-data-project.git

**Comment by olmocorell** [comment]
¡¡Soniaaaaaaaaaa!! 🚀 💪🏻 
No me explayo mucho por aquí, porque te dimos la corrección en el momento ayer. Así que espero que todos los consejos que te dimos te sirvan para mejorar este proyecto cuando acabes el bootcamp y tengas un ratito, y también te sirvan de cara a siguientes proyectos.
Recuerda que podíamos tener todas las colecciones en mongo y hacer queries del tipo near, además de pintar los markers en los mapas.
¡¡Buen trabajo!!
¡seguimooooooooooooooooos!


<img width="637" alt="pythoneverywhere 2" src="https://user-images.githubusercontent.com/57899051/107533516-4d9d1d80-6bbf-11eb-976f-35318319a824.png">
