### ISSUE TITLE
[W4-geospatial-data-project] JJ Triviño

### ISSUE THREAD

**Issue by JJTrivino** [Ironhack-Data-Madrid-Enero-2021/W4-geospatial-data-project#10]
https://github.com/JJTrivino/W4-project-geolocalization

**Comment by breogann** [comment]
Juanjo! 🙋🏻‍♂️

Vamos allá con el proyecto!

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: Perfect! No se te ha colado ningún archivo temporal/oculto. Incluyendo los tokens!
    - La organización en general está también bien, es justo como tienen que estar los proyectos.
    - Lo único que cambiaría es la carpeta de data. En data pondría sólo el input y el oputut: csv's, etc. Que por cierto, tienes un "nursery_list" en esa carpeta que no tiene extensión (lo mismo con design_studio).
    - data/prueba.-_geoquerys.ipynb lo puedes eliminar si es redundante.
- El **[README.md](http://readme.md) ✍🏻**: está genial! procura quizá no copypastear los objetivos y los requisitos.
- La **modularización 📉**: bien porque has importado las funciones en el jupyter desde otro punto. PERO, hay que atomizar funciones. En tu [utils.py](http://utils.py) tienes funciones que para ver de principio a fin tienes que hacer scroll. Si la función no cabe en una captura de pantalla, es que algo va mal (aunque que quepa no quiere decir que ncesariamente esté bien). El código: modularizado (metido en funciones) y atomizado (cumplen objetivos pequeños). La forma de integrarlo es o bien a través de callback (funciones que llaman a otras) o si se trata de un ejecutable, ir llamando a cada una de ellas, por ejemplo. Es importante para el debugging, para tu salud mental y para la escalabilidad (en el momento en el que quieras añadir/quitar alguna funcionalidad de la función vas a necesitar modificar mucho código, mientras que si lo tienes atomizado en funciones más pequeñas, te bastaría con eso).
- La función de mongo, aprovechando que la tienes en una misma "línea", puedes también definirla como tal.
- El **código 👩‍💻:**
    - Genial por poner el índice/títulos en el jupyter!
    - También por poner los docstrings 👏
    - Para la función de geocode, has hecho súper bien al poner el try/except; suele dar bastante fallo.
    - Has creado los mapas pero no los printeas (tampoco los usas en nbviewer) 😶?
    - Cuando haces el donde = input, si no pones los paréntesis, no te funciona, no?
    - Para insertar los datos en mongo, puedes también modularizarlo en un función y como parámetro poner la colección que quieres crear, el dataframe, etc.
    - Esta función:

        ```python
        def getFromDict(diccionario,mapa):
                return reduce(operator.getitem,mapa,diccionario)
        ```

        la tienes definida dentro de otra. Cuando definas una función, procura hacerlo de forma aislada. Luego puedes llamarla dentro como getFromDict().

    Respecto al **planteamiento** dos ideas generales:

    - Método deductivo: lo ideal es que vaya de lo general a lo concreto. Que partiendo de una base de datos, se acabe acotando; en vez de elegir la ubicación y luego confirmar de forma retroactiva. Es lo ideal pero sabemos que es difícil, así que siempre que esté respaldado por datos, lo damos como válido.
    - Decisiones tomadas en datos: siendo data analysts tenemos que garantizar que las decisiones que tomamos se basan en lo que trabajamos:  no pueden ser a ojo ni tomadas en base a una representación visual. Algunas formas de conseguir esto es midiendo distancias o calculando la densidad de establecimientos en un área. En tu caso, simplemente has confirmado que sí, que hay establecimientos cercanos?

    En cualquier caso, Juanjo, has cogido datos de una BBDD, los has manipulado, has cogido más información a través de una API, has sacado conclusiones y los has incluido en la base de datos. Está bien el proyecto, pero le puedes dar alguna vuelta para mejorarlo. Sigue así que para el siguiente vas a hacerlo también genial!!

    Seguimoooosss 🗺🤘
