### ISSUE TITLE
[W4-geospatial-data-project] Alex Moreno

### ISSUE THREAD

**Issue by amorenorp** [Ironhack-Data-Madrid-Enero-2021/W4-geospatial-data-project#11]
https://github.com/amorenorp/GeoSpacial_data_project

**Comment by breogann** [comment]
Álex! 🙋🏻‍♂️

Vamos allá con el proyecto!

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: Se te han colado archivos temporalse (como el DS_Store). Veo que luego lo incluiste en el .gitignore, pero git ya los tiene trackeados. Lo que tienes que hacer es:

        ```python
        git rm --cached **/*.DS_Store
        ```

        para que los destrackee. Y al estar ya incluidos en el .gitignore, no te debería dar problema.

    - Los archivos de funciones suelen ir en una carpeta de src.
    - Por la parte de img y maps, todo bien.
- El **[README.md](http://readme.md) ✍🏻**: está genial! quizá puedes aprovechar para poner el mapa que tienes exportado en el readme.
- La **modularización 📉**: genial! defines las funciones en un [archivo.py](http://archivo.py) que luego importas en el jupyter. Lo único, no te olvides de los docstrings!: para lo que sirve la función, los argumentos que recibe y lo que devuelve.
- El **código 👩‍💻:**
    - Tienes import a lo largo del jupyter, ponlos siempre al principio
    - Tienes funciones definidas: si están definidas, llévalas al [archivo.py](http://archivo.py) e impórtalas, como has hecho con el resto. Si ya está importada, puedes borrarla.
    - Para calcular la distancia dentro de un radio:

        ```python
        if dist <= 0.500:
        ```

        puedes poner como parámetro la distancia en las llamadas a foursquare (por si te viene mejor).

    - El código para crear las listas de sitios cercanos también lo puedes meter en funciones

    Respecto al **planteamiento** dos ideas generales:

    - Método **deductivo**: lo ideal es que vaya de lo general a lo concreto. Que partiendo de una base de datos, se acabe acotando; en vez de elegir la ubicación y luego confirmar de forma retroactiva. Has acotado eligiendo Londres pero luego has elegido un Starbucks aleatorio como referencia para lanzar tus queries. Pero luego calculas las distancias de las cosas que te devuelve la API con la de las empresas, ¿no?. Una forma es acotar las empresas para lanzar queries con cada una de ellas. Vamos, lo mismo que has hecho pero en vez de lanzar las llamadas con una ubicación y luego restar distancias, lanzar llamadas con cada ubicación.
    - Decisiones tomadas en **datos**: siendo data analysts tenemos que garantizar que las decisiones que tomamos se basan en lo que trabajamos:  no pueden ser a ojo ni tomadas en base a una representación visual. Algunas formas de conseguir esto es midiendo distancias o calculando la densidad de establecimientos en un área; tal y como has hecho 👏

    En cualquier caso, Álex, has cogido datos de una BBDD, los has manipulado, has cogido más información a través de una API, has sacado conclusiones y los has incluido en la base de datos. Está súper el proyecto, sólo te faltaría como algo general el modularizar más funciones y hacer los docstrings. Sigue así que para el siguiente vas a hacerlo también genial!!

    Seguimoooosss 🗺🤘
