### ISSUE TITLE
[W4-geospatial-data-project]. Alfredo Zavala

### ISSUE THREAD

**Issue by alfredozavala14** [Ironhack-Data-Madrid-Enero-2021/W4-geospatial-data-project#12]
https://github.com/alfredozavala14/geospatial-data-project

**Comment by breogann** [comment]
Alfredo! 🙋🏻‍♂️

Vamos allá con el proyecto!

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: Perfect! No se te ha colado ningún archivo temporal/oculto. Incluyendo los tokens.
    - La organización está bien. Los [archivos.py](http://archivos.py) en src y jupyter aparte.
- El **[README.md](http://readme.md) ✍🏻**: está genial que hayas explicado los pasos que has ido siguiendo. Lo que podrías haber incluido también son los mapas, que veo que los generas en el jupyter. Puedes exportar la imagen (o incluso hacer una captura; en este caso no pasa nada al no ser una gráfica de matplotlib/seaborn)  y añadirla.
- La **modularización 📉 & el código 👩‍💻**:
    - Tanto las importaciones en el jupyter como las docstrings y los comentarios están perfectos.
    - Los mapas que has creado en jupyter puedes enlazarlos a nbviewer; que ahí sí que se renderizan. El enlace sería este: [https://nbviewer.jupyter.org/github/alfredozavala14/geospatial-data-project/blob/main/work_JN/finding-a-location.ipynb](https://nbviewer.jupyter.org/github/alfredozavala14/geospatial-data-project/blob/main/work_JN/finding-a-location.ipynb)
    - Has hecho bien en definir esta función fuera:

        ```python
        def get_from_dict(dictionary,search_map):
        ```

    - Has utilizado también bastante numpy. Es algo sobre lo que está construido pandas, así que en términos de eficiencia seguro que es súper positivo.
    - Poquito más que decirte, está todo bastante bien

Respecto al **planteamiento** dos ideas generales:

- **Método deductivo:** lo ideal es que vaya de lo general a lo concreto. Que partiendo de una base de datos, se acabe acotando; en vez de elegir la ubicación y luego confirmar de forma retroactiva; que es lo que has hecho.

Edit: o sea, que lo has hecho bien vaya. Que has elegido un punto como referencia para lanzar las queries pero no te has quedado con ese porque "sí que has encontrado puntos", sino que una vez has recogido el resto de puntos, has hecho el análisis para encontrar el punto final.

- **Decisiones tomadas en datos**: siendo data analysts tenemos que garantizar que las decisiones que tomamos se basan en lo que trabajamos:  no pueden ser a ojo ni tomadas en base a una representación visual. Algunas formas de conseguir esto es midiendo distancias o calculando la densidad de establecimientos en un área. En tu caso, has utilizado ponderaciones y densidad, lo cual está perfect; pero las llamadas las has lanzado en base a un punto "arbitrario" en base al heatmap. Era un planteamiento difícil, pero lo damos por válido porque el resto está genial.

En cualquier caso, Alfredo, has:

- Cogido datos de una base de datos
- Convertido a geoJSON
- Creado la 2dsphere
- Hecho llamadas a una API
- Ploteado mapas
- Calculado la densidad de establecimientos
- Ponderado

Lo único que podría faltar es haber utilizado más mongoqueries además de las de la distancia. Pero está súper el proyecto. Sigue así que para el siguiente harás proyectazo.

Seguimoooosss 🗺🤘
