### ISSUE TITLE
[W4-geospatial-data-project] Ana G

### ISSUE THREAD

**Issue by AnaAGG** [Ironhack-Data-Madrid-Enero-2021/W4-geospatial-data-project#13]
https://github.com/AnaAGG/P3_Geospatial_Data.git

**Comment by breogann** [comment]
Ana! 🙋🏻‍♂️

Vamos allá con el proyecto!

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: Perfect! No se te ha colado ningún archivo temporal/oculto. Incluyendo los tokens!
    - La organización está perfecta. No tienes archivos que no añadan valor, tienes los datos organizados por input/oputput y por fuente, la src con los .py con nombres significativos y los notebooks numerados según el orden 👏 Sin entrar a leer el código (o el readme) puedo entender el flujo de trabajo del proyecto.
- El **[README.md](http://readme.md) ✍🏻**: súuper top el readme. Por ponerme quisquilloso, incluiría la parte en la que insertas los datos de la API en la base de datos en el esquema.
    - "Before first filtering using MongoDB I obtained a set of XXX companies with coordinates located in Madrid, Barcelona, Bilbao, Gijón." O sea, primero elegiste esas ciudades y luego filtraste por el resto de criterios en Mongo?
    - Bueno, el readme está perfecto. Creo que un buen criterio para hacer buenos readmes es seguir la estructura de publicaciones científicas, donde hay introducción, métodos, datos, conclusiones (y si quieres, discusión). Tal y como lo tienes está muy 🔝
- La **modularización 📉 & el código 👩‍💻**:
    - Tanto las importaciones en el jupyter, como los docstrings están perfectas (incluso especificando el type de los args 🤩).
    - Muy bien al poner el try/except de geocode, que es algo que falla bastante.
    - Esta función:

        ¿qué error te da? ¿es por el nombre del a colección?

        ```python
        def connection (gdf, nombre):
        ```

    - Poquito más que decirte, está todo bastante bien

Respecto al **planteamiento** dos ideas generales:

- **Método deductivo:** lo ideal es que vaya de lo general a lo concreto. Que partiendo de una base de datos, se acabe acotando; en vez de elegir la ubicación y luego confirmar de forma retroactiva. Y si he entendido bien, es lo que has hecho 👏 (filtrando las ciudades con las queries de mongo y luego lanzando llamadas de API's). Sí que es cierto que has acabado eligiendo una ciudad pero no has elegido un punto concreto, ¿no?
- **Decisiones tomadas en datos**: siendo data analysts tenemos que garantizar que las decisiones que tomamos se basan en lo que trabajamos:  no pueden ser a ojo ni tomadas en base a una representación visual. Algunas formas de conseguir esto es midiendo distancias o calculando la densidad de establecimientos en un área. En tu caso, has utilizado ponderaciones, lo cual está perfect.

En cualquier caso, Ana, has cogido datos de una BBDD, los has manipulado, has cogido más información a través de una API, has sacado conclusiones y los has incluido en la base de datos. Está súper el proyecto. Sigue así que para el siguiente vas a petarlofuerte también.

Seguimoooosss 🗺🤘
