### ISSUE TITLE
[geospacial-data-project] Sergio Calero

### ISSUE THREAD

**Issue by SergioCaler0** [Ironhack-Data-Madrid-Enero-2021/W4-geospatial-data-project#14]
https://github.com/SergioCaler0/geospatial_data_project

**Comment by breogann** [comment]
Sergio! 🙋🏻‍♂️

Vamos allá con el proyecto!

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: Has utilizado el .env para los tokens, lo cual 👌. Pero se te han colado archivos temporal: __**pycache__.** Como git ya lo tiene trackeado, lo que tienes que hacer es:

        ```python
        git rm --cached **/*__pycache__
        ```

        para que los destrackee. Lo mismo con .ipynb_checkpoints. Y luego incluirlo en el gitignore. Échale un ojo a los .gitignore que tenemos en los labs, ahí hay varios archivos que tenemos ignorados de forma recursiva.

- El **[README.md](http://readme.md) ✍🏻**: ok! Has incluido una captura del mapa. Por añadir más cosas, algo que puedes hacer es rellenar lo que has utilzado. Es decir, poner que has utilizado una base de datos en mongo, la API que has usado, etc. Y las librerías!
- La **modularización 📉**:
    - Has definido las funciones en el api_search.py pero los tokens los has dejado fuera. No pasa nada por dejarlos fuera, pero luego los tienes que volver a definir en el jupyter: si los guardas dentro ya te los llevas contigo.
    - Te faltan los docstrings 🔪: documenta tu código como te gustaría encontrártelo.

        ```python
        def suma(a,b):
        '''This functions adds numbers
        Args: two int
        Returns: one number result of the addition'''
        	return a + b
        ```

         pon también comentarios con almohadilla para cosas más 

        Ten en cuenta que:

        ```python
        '''These functions take the number from establishment 
        near the companies, and ponder to take points to choose one of them'''

        def get_points_starbucks(lst):
        ```

        cuando llames a la documentación de esa función:

        ```python
        get_points_starbucks.__doc__
        ```

        no te devolverá nada. Igualmente es útil para el lector que abre el archivo.py.

- El **código 👩‍💻:**
    - El código está bien! Simplemente la organización que te comentaba más arriba.

    Respecto al **planteamiento** dos ideas generales:

    - Método **deductivo**: lo ideal es que vaya de lo general a lo concreto. Que partiendo de una base de datos, se acabe acotando; en vez de elegir la ubicación y luego confirmar de forma retroactiva. Es decir, que el planteamiento no era necesariamente elegir una ubicación y entonces buscar lo que está cercano, sino al revés.
    - Decisiones tomadas en **datos**: siendo data analysts tenemos que garantizar que las decisiones que tomamos se basan en lo que trabajamos:  no pueden ser a ojo ni tomadas en base a una representación visual. Algunas formas de conseguir esto es midiendo distancias o calculando la densidad de establecimientos en un área. Lo que has hecho simplemente es sacar el punto más cercano, pero eso no lo utilizas como criterio, sino como resultado.

    En resumen, Sergio, has:

    - Filtrado la base de datos con mongoqueries
    - Hecho llamadas a API
    - Ploteado los mapas

    👏

    Peeero lo que me falta que utilices geoqueries (con geoJSON) y que utilices alguna técnica como la resta de distancias o cálculo de densidad (nº establecimientos en un radio) y que el planteamiento no sea retroactivo. Es sólo cuestión de darle alguna vuelta. Ánimo Sergio, que el siguiente lo sacas súper bien seguro!

    Seguimoooosss 🗺🤘
