### ISSUE TITLE
[W4-geospatial-data-project] Jean Charles Yamada

### ISSUE THREAD

**Issue by yamadajc** [Ironhack-Data-Madrid-Enero-2021/W4-geospatial-data-project#16]
https://github.com/yamadajc/geospatial-data-project

**Comment by breogann** [comment]
Jeancha! 🙋🏻‍♂️

Dijimos que te daríamos un feedback superficial al ser una re-entrega, pero voy a intentar comentarte todo lo que vea; aunque no haya sido inmediato el feedback te vale para el futuro y para mejorar proyectos después del bootcamp. 

Vamos allá con el proyecto!

Lo primero que veo es que has añadido casi todos los archivos a través de upload en vez de hacer commits a través de la terminal. No recuerdo si en el resto de los proyectos también lo haces así, pero piérdele el miedo a la terminal y utilízala siempre en la medida de lo posible.

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: No tienes. Aquí utilizas API's. ¿no tienes el token? Obviamente el `.env` no tienes que subirlo, pero por eso precisamente el .gitignore, para que cuando subas archivos a través de la terminal, no se te suban los que no te hacen falta/no se tienen que subir.
    - Por lo demás, la organización de carpetas está perfect. Incluida la numeración de los jupyters. Quizá puedes separar la de data en input/output, para explicitar qué ha entrado y cómo han quedado esos datos tras el procesamiento; pero eso es más decisión personal.
- El **[README.md](http://readme.md) ✍🏻**: Siempre añade toda la información que puedas/creas que puede añadir valor. Por ejemplo, los mapas que generes. Puedes usar nbviewer con el enlace a tu jupyter para renderizarlo. Cuidado con las erratasss ⚠️
- La **modularización 📉**: está bien, pero puede estar mejor si:
    - Separas las funciones por obetivo: no tienes tampoco muchas, pero puedes hacer un archivo para las de la API y otro para las mongoqueries.
    - En el segundo jupyter importas las funciones de fapis.py, pero tienes un montón de código que también puedes meter en funciones parametrizadas. Al final re-escribes código para Starbucks, museos y aeropuertos. Entiendo que cada json tiene una estructura diferente, pero seguro que lo puedes refactorizar y parametrizar.
- El **código 👩‍💻:**
    - En general, están super bien los docstrings y los comentarios. En algunas funciones has hecho el docstring con argumentos y con lo que recibe y devuelve, en otras sólo lo que hace la función, etc. Si estandarizas la estructura, te será más fácil en el futuro hacerlo. Pero muy bien los comentarios.
    - En fapis.py:

        ```python
        db = client.geoloco # genera bbdd con un nombre en este caso geoloco
        ```

        no crea la base de datos, sino que la guarda en una variable.

    Respecto al **planteamiento** dos ideas generales:

    - Método **deductivo**: lo ideal es que vaya de lo general a lo concreto. Que partiendo de una base de datos, se acabe acotando; en vez de elegir la ubicación y luego confirmar de forma retroactiva. Era un planteamiento difícil, pero creo que lo has enfocado bien.
    - Decisiones tomadas en **datos**: siendo data analysts tenemos que garantizar que las decisiones que tomamos se basan en lo que trabajamos:  no pueden ser a ojo ni tomadas en base a una representación visual. Algunas formas de conseguir esto es midiendo distancias o calculando la densidad de establecimientos en un área; tal y como has hecho 👏


    En resumen, Jeancha, has:

    - Filtrado la base de datos con mongoqueries
    - Utilizado geoJSON
    - Hecho llamadas a API
    - *Ploteado los mapas ❌ (no era obligatorio)*

    Obviamente tiene mejoras, como todos los proyectos, porque es casi imposible que lo hagáis perfecto de primeras; pero eso no quita que hayas llegado a objetivos  y que hayas conseguido algo que hace unas semanas atrás habría sido impensable. 

    It **IS** a Jeancha

    Seguimoooosss 🗺🤘

**Comment by breogann** [comment]
meme de calidad cuestionable, pero aquí va
![image](https://user-images.githubusercontent.com/54676992/110688168-94435f00-81e1-11eb-8f00-68fbc437788a.png)
