### ISSUE TITLE
[W4-geospatial-data-project] Santiago Hartmann

### ISSUE THREAD

**Issue by santhart97** [Ironhack-Data-Madrid-Enero-2021/W4-geospatial-data-project#17]
https://github.com/santhart97/Geospatial-Data-Santiago/blob/main/Project.ipynb

**Comment by breogann** [comment]
Santiago! 🙋🏻‍♂️

Vamos allá con el proyecto!

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: No se te ha colado ningún archivo temporal/oculto. Incluidos los tokens! 👌
- El **[README.md](http://readme.md) ✍🏻**: no lo tienes Santiago 🔪 Haz el readme incluyendo toda la info que te gustaría encontrarte: lo que has hecho, cómo, qué tecnologías has utilizado, etc. Y el mapa! Normalmente hacer capturas se desaconsejan, pero para los mapas, no pasa nada. Si no, incluye el nbviewer (te lo pongo más abajo).
- La **modularización 📉**:
    - La idea es que las funciones que utilices en jupyter las parametrices y las modularices en un [archivo.py](http://archivo.py). Luego, una vez definidas en ese archivo las importes en el jupyter.
    - Las funciones tienen que estar con docstrings: documenta tu código como te gustaría encontrártelo.

        ```python
        def suma(a,b):
        '''This functions adds numbers
        Args: two int
        Returns: one number result of the addition'''
        	return a + b
        ```

         pon también comentarios con almohadilla para cosas más 

        Ten en cuenta que:

        ```python
        '''These functions take the number from establishment 
        near the companies, and ponder to take points to choose one of them'''

        def get_points_starbucks(lst):
        ```

        cuando llames a la documentación de esa función:

        ```python
        get_points_starbucks.__doc__
        ```

        no te devolverá nada. Igualmente es útil para el lector que abre el archivo.py.

- El **código 👩‍💻:**
    - Genial por los comentarios y los títulos!
    - Para los mapas, como no se renderizan en github, puedes utilizar nbviewer. Este sería el enlace: [https://nbviewer.jupyter.org/github/santhart97/Geospatial-Data-Santiago/blob/main/Project.ipynb](https://nbviewer.jupyter.org/github/santhart97/Geospatial-Data-Santiago/blob/main/Project.ipynb)
    - Genial por usar apply!
    - Aquí Santiago:

        ```python
        #Because I only want London I drop all the other cities
        Lnd_offices = join[(join.city != 'San Jose') & (join.city != 'Los Angeles') & (join.city != 'New York') & (join.city != 'Chicago') & (join.city != 'Toronto') & (join.city != 'Singapore') & (join.city != 'Zurich') & (join.city != 'Chiyoda-ku Tokyo') & (join.city != 'San Francisco') & (join.city != 'Moscow') & (join.city != 'Munich') & (join.city != 'Hong Kong')  & (join.city != 'Paris')  & (join.city != 'Sydney') & (join.city != 'Montreal')  & (join.city != 'Ljubljana') & (join.city != 'Stockholm')  & (join.city != '')  & (join.city != 'Madrid')  & (join.city != 'Hamburg') & (join.city != 'Lod') & (join.city != 'Cologne') & (join.city != 'Celebration') & (join.city != 'New York City') & (join.city != 'Beijing')  & (join.city != 'Dublin') & (join.city != 'Waterford') & (join.city != 'Edinburgh')  & (join.city != 'Cambridge') & (join.city != 'Christchurch') & (join.city != 'Houston') & (join.city != 'Atlanta') & (join.city != 'Dallas') & (join.city != 'Denver') & (join.city != 'Costa Mesa') & (join.city != 'Ft. Lauderdale') & (join.city != 'Seattle') & (join.city != 'Herndon') & (join.city != 'Tokyo') & (join.city != 'Jersey City') & (join.city != 'Chao Yang') & (join.city != 'Beijing') & (join.city != 'Milton Keynes')]
        ```

        no dropees todo, selecciona sólo lo que te interesa.

    - ¿Por qué  eliges wetpaint? ¿es la única que está en Londres?
    - Has navegado bien por los json!
    - Has subido el client_id y el client_secret!!! ⚠️ utiliza el ``.env`` para cargar esas variables!

    Respecto al **planteamiento** dos ideas generales:

    - Método **deductivo**: lo ideal es que vaya de lo general a lo concreto. Que partiendo de una base de datos, se acabe acotando; en vez de elegir la ubicación y luego confirmar de forma retroactiva. Es decir, que el planteamiento no era necesariamente elegir una ubicación y entonces buscar lo que está cercano, sino al revés. Porque al final, siempre que lances una búsqueda de un starbucks en una ciudad, te devolverá alguno. Esté a 200m o 20km, pero te devolverá algo casi siempre. Entonces, ¿en qué momento desestimarías que esa ubicación no te compensa?
    - Decisiones tomadas en **datos**: siendo data analysts tenemos que garantizar que las decisiones que tomamos se basan en lo que trabajamos:  no pueden ser a ojo ni tomadas en base a una representación visual. Algunas formas de conseguir esto es midiendo distancias o calculando la densidad de establecimientos en un área. Lo que has hecho simplemente es sacar el punto más cercano, pero eso no lo utilizas como criterio, sino como resultado.

    En resumen, Santiago, has:

    - Has hecho una mongoquery (solo 🥲)
    - Hecho llamadas a API y navegado por los json
    - Has transformado a geoDataFrame
    - Ploteado los mapas

    👏

    Peeero lo que me falta que utilices geoqueries (con geoJSON) y que utilices alguna técnica como la resta de distancias o cálculo de densidad (nº establecimientos en un radio) y que el planteamiento no sea retroactivo. También que hagas readme y archivo de funciones. Ánimo Santiago, que el siguiente lo sacas súper bien seguro!

    Seguimoooosss 🗺🤘
