### ISSUE TITLE
[W4-geospatial-data-project] Mario García

### ISSUE THREAD

**Issue by MarioGar25** [Ironhack-Data-Madrid-Enero-2021/W4-geospatial-data-project#2]
My repo: https://github.com/MarioGar25/Geospatial-project
![descargasssss](https://user-images.githubusercontent.com/74923690/106927735-bfceb780-6712-11eb-94f6-a3a1786a530e.jpg)

**Comment by breogann** [comment]
Mario! 🙋🏻‍♂️

Vamos allá con el proyecto!

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: Se te ha colado un archivo temporal: __**pycache__.** Como git ya lo tiene trackeado, lo que tienes que hacer es:

        ```python
        git rm --cached **/*__pycache__
        ```

        para que los destrackee. Y luego incluirlo en el gitignore. Por lo demás, genial porque no has subido el token. Échale un ojo a los .gitignore que tenemos en los labs, ahí hay varios archivos que tenemos ignorados de forma recursiva.

- El **[README.md](http://readme.md) ✍🏻**: está bien, pero procura no copiar nuestra plantilla. Añade toda la información que puedas/creas que puede añadir valor. Por ejemplo, el mapa que generas al final del jupyter, los has exportado como html. Pero luego no lo renderizas en ningún sitio? También puedes usar nbviewer. El enlace sería este: [https://nbviewer.jupyter.org/github/MarioGar25/Geospatial-project/blob/main/Finding.ipynb](https://nbviewer.jupyter.org/github/MarioGar25/Geospatial-project/blob/main/Finding.ipynb)
- La **modularización 📉**: está genial. Pero tienes funciones que sólo tienen una línea y que además se repiten:

    ```python
    def extract_city(dic):    
        ''' extracts the city from a dictionary '''
        return dic.get("city")

    def extract_latitude(dic):
        ''' extracts the latitude from a dictionary '''
        return dic.get("latitude")
    ```

    Eso se puede refactorizar si las parametrizas de tal forma que reciban dos argumentos.

    Por la parte de docstrings y de comentarios perfecto. 

    Ten en cuenta que:

    ```python
    '''These functions take the number from establishment 
    near the companies, and ponder to take points to choose one of them'''

    def get_points_starbucks(lst):
    ```

    cuando llames a la documentación de esa función:

    ```python
    get_points_starbucks.__doc__
    ```

    no te devolverá nada. Igualmente es útil para el lector que abre el archivo.py.

- El **código 👩‍💻:**
    - Veo en el jupyter que utilizas las funciones que te comentaba en el apply. Entiendo que definías los argumentos dentro de ella porque el apply no te acepta que se lo pases a una serie si le metes parámetros, ¿puede ser? Mira, te paso esto:

        ```python
        my_series.apply(your_function, args=(2,3,4), extra_kw=1)
        ```

        [https://www.kite.com/python/answers/how-to-apply-a-function-with-multiple-arguments-to-a-pandas-dataframe-in-python](https://www.kite.com/python/answers/how-to-apply-a-function-with-multiple-arguments-to-a-pandas-dataframe-in-python)

        otra forma también sería guardarlo en una variable:

        ```python
        #La función
        def extract (dic, "something"):    
            ''' extracts something from a dictionary '''
            return dic.get("something")

        #La variable
        extract_latitude = extract(dic, "latitude")

        #El apply
        df["latitude"] = df["offices"].apply(extract_latitude)
        ```

        aunque desde luego no es lo más eficiente.

    - Acabas eligiendo Globant pero Razz tiene más puntos, ¿no?

    Respecto al **planteamiento** dos ideas generales:

    - Método **deductivo**: lo ideal es que vaya de lo general a lo concreto. Que partiendo de una base de datos, se acabe acotando; en vez de elegir la ubicación y luego confirmar de forma retroactiva. Era un planteamiento difícil, pero lo damos por válido porque elegir San Francisco está basado en la cantidad de empresas y elegir las coordenadas iniciales sobre la que lanzar las queries son las que te da geocode.
    - Decisiones tomadas en **datos**: siendo data analysts tenemos que garantizar que las decisiones que tomamos se basan en lo que trabajamos:  no pueden ser a ojo ni tomadas en base a una representación visual. Algunas formas de conseguir esto es midiendo distancias o calculando la densidad de establecimientos en un área; tal y como has hecho 👏

    En resumen, Mario, has:

    - Filtrado la base de datos con mongoqueries
    - Utilizado geoJSON
    - Hecho llamadas a API
    - Ploteado los mapas
    - Insertado los mapas en mongo

    Está muy bien el proyecto!

    Seguimoooosss 🗺🤘
