### ISSUE TITLE
[W4-geospatial-data-project] Xabier Arrieta

### ISSUE THREAD

**Issue by XabierArrieta** [Ironhack-Data-Madrid-Enero-2021/W4-geospatial-data-project#3]
https://github.com/XabierArrieta/geospatial-project

**Comment by olmocorell** [comment]
¡¡Hola Xabiiiiiiiii!! 🚀 💪🏻 
¡¡Aquí estoy para contarte algunas cosinas sobre tu geomongoproyecto!!

### Readme
¡¡Está perfectoooooooooo!! ¡Enhorabuena! Sigues todos los consejos que te hemos dado y es un readme completo con todo lo que se requiere, bien explicado. Una carta de presentación perfecta para tu proyecto.


### Code/Repository structure
La estructura y organización del repositorio está perfecta, lo único que... ¿qué ha pasado aquí?
<img width="591" alt="Captura de pantalla 2021-02-11 a las 16 55 06" src="https://user-images.githubusercontent.com/57899051/107661792-e7c99800-6c89-11eb-87a3-5818e6b82df5.png">
funcionesok.py 🔥 🔥 
Ponemos nombres descriptivos a los archivos de funciones, igual que a las funciones, variables, etc.
¿Qué tipo de funciones contiene ese archivo? No lo sabemos, solo sabemos que están ok jeje.


### Code efficiency / Code syntax (conventions)
En [este](https://nbviewer.jupyter.org/github/XabierArrieta/geospatial-project/blob/main/notebooks/01.%20Filtro%20empresa.ipynb) haces genial en comenzar el proyecto haciendo una query complicada en mongo. Es una buena forma de demostrar lo que has aprendido en esta semana de mongo.
<img width="1035" alt="Captura de pantalla 2021-02-11 a las 17 48 07" src="https://user-images.githubusercontent.com/57899051/107668762-4f371600-6c91-11eb-9401-8ef16e58ea78.png">

Lo malo de este planteamiento, es que desde el princpio te limitas a una oficina. La idea era que los datos nos llevaran a la elección de la localización donde íbamos a poner la oficina, no que encontráramos una oficina y después buscáramos el resto de elementos. ¿Entiendes?
Aún así, podría haber entendido que tomaras una ciudad como punto de partida, porque entiendo que hay que partir de algo, que es difícil el planteamiento de la nada de este proyecto.

Ojo por aquí, que importamos módulos que realmente no nos hacen falta dentro de este archivo.
<img width="733" alt="Captura de pantalla 2021-02-11 a las 17 54 47" src="https://user-images.githubusercontent.com/57899051/107669644-3d09a780-6c92-11eb-9a76-1806f59cf6b2.png">

Aquí:
<img width="640" alt="Captura de pantalla 2021-02-11 a las 17 56 06" src="https://user-images.githubusercontent.com/57899051/107669808-6de9dc80-6c92-11eb-8107-7db3326b1c9a.png">
De aquí puedes sacar un par de funciones, recuerda que intentamos hacer funciones de propósito único. ¿Vale? Esto se puede atomizar un poquito.

Por otra parte, haces todo lo que se te pide y has hecho un buen proyecto.

Tus puntos fuertes son: el manejo de las queries, que has cargado los datos en mongo para usar las queries de tipo near tal y como se pedía. Has pintado mapas, manejas los json. Las funciones están documentadas...
En general has hecho un muy muy buen trabajo. Así que .... ¡¡¡ENHORABUENA!!!
Estoy muy orgullosa y muy contenta de tu evolución Xabi. Lo estás haciendo genial ¿ves lo que estás aprendiendo?
¡¡Es FLIPANTE!!


### Improvements
- Atomización del código en funciones.
- Estaría guay que encontraras otra forma de abordar el problema para llegar al punto exacto basándote en los datos en vez de buscar los datos a posteriori después de tener ya una localización.

¡¡Y eso es todo!! ¡¡Sigue así Xabiiiiiiiiiiiiiiiiiii!!


![unnamed](https://user-images.githubusercontent.com/57899051/107670801-67a83000-6c93-11eb-9f58-fffd75af8e35.png)
