### ISSUE TITLE
[W4-geospatial-data-project] Floren Gutiérrez

### ISSUE THREAD

**Issue by florengutierrez** [Ironhack-Data-Madrid-Enero-2021/W4-geospatial-data-project#5]
https://github.com/florengutierrez/Geospatial-Project

**Comment by olmocorell** [comment]
¡¡Hola Floreeeeeeeeeeeeeeeeen!! 🚀 💪🏻 
Te cierro la issue sin explayarme por aquí porque ya te hemos dado feedback esta mañana entre todas. Espero que te hayas quedado con todos los consejitos que te hemos dado.
¡¡Muy buen trabajo y enhorabuena por tu proyecto!! 

![ac470b826e3990c09327a3fdc5855cc9](https://user-images.githubusercontent.com/57899051/107365469-21a96b80-6add-11eb-9ede-f1bff523b8c6.jpg)
