### ISSUE TITLE
[W4-geospatial-data-project] Ángela Navarro

### ISSUE THREAD

**Issue by angelanavarrog** [Ironhack-Data-Madrid-Enero-2021/W4-geospatial-data-project#6]

**Comment by angelanavarrog** [comment]
https://github.com/angelanavarrog/W4-geospatial-data-project

**Comment by angelanavarrog** [comment]
https://github.com/angelanavarrog/-Project-geospatial-Angela-Navarro

**Comment by olmocorell** [comment]
¡¡Hola Ángelaaaaaaaaa 🚀 💪🏻  !! 
Te cuento un poquito sobre tu proyecto. Está muy bien porque has utilizado los requisitos que pedíamos, es decir, has hecho llamadas a una API, lo has guardado en mongo, has hecho los mapas 2d, has hecho geoqueries del tipo near .... todo esto está perfecto.
Lo único que está al revés es el planteamiento...digamos que tú has partido de un punto y de ahí te has puesto como a "justificar" que había cosas cerca. Pero no son los datos los que te han llevado al punto, que era lo que pedíamos....

### Readme
¡¡Enhorabuena!! muy buen trabajo, está genial pero... ¡el stack de tecnologías!
Pon abajo del todo un apartado de "tecnologías utilizadas" con enlaces a la documentación ¿vale?

### Code/Repository structure
¿Por qué el .gitignore se llama .ignore? Lo curioso... ¿funciona?
<img width="581" alt="Captura de pantalla 2021-02-11 a las 11 03 44" src="https://user-images.githubusercontent.com/57899051/107622880-d025eb80-6c58-11eb-9070-6ead616a9d7b.png">

### Code efficiency / Code syntax (conventions)
Me ha faltado aquí que hicieras un archivo de funciones y que automatices algunos procesos. Es decir, puedes automatizar las queries, el extraer las coordenadas en plan esto:
<img width="708" alt="Captura de pantalla 2021-02-11 a las 11 26 14" src="https://user-images.githubusercontent.com/57899051/107624993-f5682900-6c5b-11eb-8d83-f1fff75aee26.png">


### Improvements
- Tecnologías en readme
- Planteamiento del proyecto
- Atomización del código en funciones

Esas son las cositas que te digo, en general el proyecto está genial en cuanto a que tienes todo lo que se pide, creas el index 2d, haces las queries tipo near, pintas mapas.... ¡pero! ojo con el planteamiento, porque el nivel de dificultad cambia en tanto que necesitamos elegir un lugar al que nos han llevado los datos y no elegir un lugar al azar y luego justificarlo a posteriori... si no, demostrar con datos y justificar nuestra decisión con datos.
¡¡Enhorabuena por el trabajo!! ¡¡Sigue así Ángelaaaaaaaaaaaaaaa!!

![images](https://user-images.githubusercontent.com/57899051/107625732-10876880-6c5d-11eb-8261-31b14ad60fce.jpg)
