### ISSUE TITLE
[Proyecto W4 de datos geoespaciales] AnadeLuna

### ISSUE THREAD

**Issue by AnadeLuna** [Ironhack-Data-Madrid-Enero-2021/W4-geospatial-data-project#7]
https://github.com/AnadeLuna/Proyecto_DatosGeoespaciales

**Comment by breogann** [comment]
Ana! 🙋🏻‍♂️

Vamos allá con el proyecto!

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: Perfect! No se te ha colado ningún archivo temporal/oculto. Incluyendo los tokens.
    - La organización está bien, pero dos cosas:
        - Separa los [archivos.py](http://archivos.py) de los jupyter. Puedes o bien dejar los jupyter a nivel de root o meterlos en una carpeta.
        - No llames al archivo "funciones.py". Llámalo según la función que cumpla lo que contenga. Si todas las funciones son de geoqueries, lo puedes llamar geoqueries.py. Si tienes funciones de limpieza, otro archivo aparte que sea [cleaning.py](http://cleaning.py), y así.
        - Nombra los jupyters también según el contenido que tengan. Procura organizar el repo de tal forma que sin llegar a abrir ningún archivo el lector sea capaz de entender el flujo de trabajo. Piensa que los lectores pueden ser recruiters, compañeros con los que trabajes en equipo, etc.
- El **[README.md](http://readme.md) ✍🏻**: está bien porque explicas lo que haces, pero el objetivo del proyecto siempre es dar respuesta a tu pregunta inicial. Es decir, tu objetivo es encontrar la mejor ubicación, y eso lo consigues a través de llamadas a API's, mongoqueries, etc. Puedes también incluir los mapas (para gráficas nunca hagas capturas porque se pueden guardar las figuras, pero para los mapas es más complicado y se puede hacer captura).
- La **modularización 📉 & el código 👩‍💻**:
    - Pones las docstrings pero las pones antes de la función. Las ponemos dentro, inmediatamente después del "def" porque al llamar a la documentación:

        ```python
        geo_data.__doc__
        ```

        python te devuelve el docstring. Si está escrito fuera, no te devuelve nada. También especificamos los argumentos y lo que devuelve. Como norma general, haz la documentación como te gustaría encontrártelo. Una vez hecho el docstring, los comentarios por línea puedes ponerlos con almohadillas.

    - Procura no definir funciones dentro de funciones. En tu caso, tenías esta:

        ```python
        def getFromDict(dictionary,maps):
        ```

        dentro de otra. Si llamamos a funciones dentro de otras, pero no las definimos. Precisamente el objetivo que perseguimos al hacer funciones pequeñas, atomizadas (que cumplen un objetivo pequeño) es para simplicidad del código y para debuggear en el futuro. Si están separadas, es más fácil encontrar el error. 

    - Los mapas que has creado en jupyter puedes enlazarlos a nbviewer; que ahí sí que se renderizan, tan sólo es cuestión de añadir el enlace de tu notebook aquí: [https://nbviewer.jupyter.org](https://nbviewer.jupyter.org/)
    - Por lo demás el código está bien!

Respecto al **planteamiento** dos ideas generales:

- **Método deductivo:** lo ideal es que vaya de lo general a lo concreto. Que partiendo de una base de datos, se acabe acotando. Sí que has hecho mongoqueries, pero:
    - Has elegido California de forma ¿arbitraria?
    - Dentro de California, ¿por qué te quedas con San Mateo?
- **Decisiones tomadas en datos**: siendo data analysts tenemos que garantizar que las decisiones que tomamos se basan en lo que trabajamos: no pueden ser a ojo ni tomadas en base a una representación visual. Algunas formas de conseguir esto es midiendo distancias o calculando la densidad de establecimientos en un área. En tu caso, no devuelves una ubicación, sino que añades puntos al mapa.

Lo que me falta en este proyecto es: que hubieras utilizado geoqueries (con geoJSON), que hubieras insertado los datos de las llamadas a las API's en mongo & sobre todo que hubieras elegido un punto como respuesta a qué lugar sería el mejor, en vez de sólo visualizar: o bien midiendo densidad de establecimientos o calculando distancias.

En cualquier caso, Ana, has:

- Hecho mongoqueries
- Hecho llamadas a API
- Ploteado mapas

Está bien el proyecto, pero me falta un par de vueltas con lo que te pongo arriba. 

Seguimoooosss 🗺🤘
