### ISSUE TITLE
[W4-geospatial-data-project] Carlota Portillo

### ISSUE THREAD

**Issue by xarlomi** [Ironhack-Data-Madrid-Enero-2021/W4-geospatial-data-project#8]
vamossssss!!!v https://github.com/xarlomi/geospatial-data-project

**Comment by breogann** [comment]
Carlota! 🙋🏻‍♂️

Dijimos que te daríamos un feedback superficial al ser una re-entrega, pero voy a intentar comentarte todo lo que vea; aunque no haya sido inmediato el feedback te vale para el futuro y para mejorar proyectos después del bootcamp. 

Vamos allá con el proyecto!

Estoy seguro que si ves el proyecto ahora, tal y como estás llevando el final, tú misma vas a ver los mismo comentarios que yo jajaja, te voy contando: 

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: nada que decir. Lo tienes y has incluido el .env.
    - Los notebooks y los csv, please, en carpetas. Y también numéralos por orden lógico: primero queries, luego limpieza, luego apis, luego visualización etc.
- El **[README.md](http://readme.md) ✍🏻**: Siempre añade toda la información que puedas/creas que puede añadir valor. Por ejemplo, los mapas que generes. Puedes usar nbviewer con el enlace a tu jupyter para renderizarlo.
- La **modularización 📉**: no está, pero ya sabes cómo hacerla! Varios [archivos.py](http://archivos.py) con funciones separadas según objetivo e importadas en los jupyter.
- El **código 👩‍💻:**
    - Súper bien que hayas creado funciones dentro de los jupyters en vez de utilizar sólo celdas!
    - Y esto también:

        ```python
        map(lambda x: str(x)!="None")
        ```

    - CARLOTA EL TOKEN EN EL JUPYTERRRRRR DE API_REQUESTS 🔪
    - En ese mismo jupyter defines la función para llamar a tres cosas diferentes, pero luego haces el mismo procesamiento de los datos. Puedes incluirlo en la función para refactorizarlo. En general eso lo puedes hacer para todo el notebook. Pero nada que no sepas ya!
    - En general, te faltan los docstrings y comentarios.

    En resumen, Carlota, has:

    - Filtrado la base de datos con mongoqueries
    - Hecho llamadas a API
    - Ploteado los mapas

    Tienes cosas que puedes mejorar, pero viendo cómo estás llevando el proyecto, veo que lo tienes 100% claro y que de ponerte a darle una vuelta, lo dejas genial.

    Seguimoooosss 🗺🤘
