### ISSUE TITLE
[W4-geospatial-data-project] Antonio García

### ISSUE THREAD

**Issue by antoniogarciagiron** [Ironhack-Data-Madrid-Enero-2021/W4-geospatial-data-project#9]
https://github.com/antoniogarciagiron/geospatial-data-project.git

**Comment by olmocorell** [comment]
¡¡Hola Hola Toniiiiiiiiiii !! 🚀 💪🏻 
¡¡Vengo a contarte cositas sobre tu proyecto!!

### Readme
Está **GENIAL**, de verdad, realmente genial. ¡¡Enhorabuena!! La explicación, el tema de los Peaky Blinders... espectáculo.
Lo único que me falta, por ponerme tiquismiquis, como siempre digo, al final es un apartado de stack de tecnología donde menciones todas las librerías utilizadas y pongas enlaces a la documentación. 

### Code/Repository structure
Matrícula de honor en la estructura de tu repositorio. ¡¡Gracias!! 🥇 

### Code efficiency / Code syntax (conventions)
Funciones bien documentadas, eficientes, parametrizadas, que cumplen su propósito. Enhorabuena, has escrito un código muy eficiente en este proyecto.


### Improvements
Casi no te voy a poner mejoras en este apartado porque tu proyecto está realmente bien, de verdad. Buscas una ciudad para tomar una decisión y a partir de ahí te respaldas con datos, con lo que te da la api de foursquare y haces el centroide. Está perfecto que hagas ese cálculo de distancias. Me gusta que tengas funciones para todo y las vayas llamando desde el jupyter. Está muy muy bien, de verdad. 
Así que te pongo un par de mejoras: 

- Uso de mongodb y 2dsphere para hacer geoqueries
- Readme enlaces a documentación

He echado de menos que volcaras todos los datos a mongo y trabajaras con el 2dsphere e hicieras geoqueries dentro de mongo. Pero para el camino que has seguido, realmente no te hacía falta, pero bueno, era parte de lo que se esperaba también por haberlo dado en clase esta semana.
Pero bueno, no pasa nada, porque tu proyecto está súper bien y respaldas la decisión en datos, que era lo que había que hacer, no simplemente mirar en un mapa y buscar un punto. Si no utilizar los datos para calcular distancias.
¡¡Bien hecho Toni!! ¡¡Buen trabajoooooooooooo!!


![welcome-to-mongodb](https://user-images.githubusercontent.com/57899051/107636098-72030380-6c6c-11eb-9f9d-2844a34fe417.jpg)
